a=str(input("adjective "))
b=str(input("noun "))
c=str(input("adjective "))
d=str(input("adjective "))
e=str(input("noun "))
f=str(input("verb "))
g=str(input("noun "))
h=str(input("noun "))
i=str(input("noun "))
j=str(input("adjective "))
k=str(input("verb "))
l=str(input("noun "))
print(f"the {a} {b} was very {c}, however the {d} {e} was disapproving of {a} {b}'s {f}ing. Because of this the nation of {g} went to war with the nation of {h} over the {b} controversy. The {i} of the {g} nation declared the {b} a {j} {k}ing {l}. The war ended the world!")
while True: pass